### ISSUE TITLE
It's not working? How to access settings?

### ISSUE THREAD

**Issue by DeltaGarnet** [atahabaki/quickie#1]
I tried !y test and !w test and neither work. I am on firefox.

**Comment by atahabaki** [comment]
It's usage says, "!" then space or tab to activate the extension then whatever the shortcut is.

**Comment by atahabaki** [comment]
Actually, there's no settings. I'm working on [astral](https://github.com/atahabaki/astral), which is better. It is not a browser extension. It is a server that serves the exact same purpose of Quickie and DuckDuckGo !Bangs. But it is WIP.

**Comment by DeltaGarnet** [comment]
Thank you. You should change the addon description on firefox then, because it literally says to use it like !y and so on.

**Comment by atahabaki** [comment]
Oh, I'm sorry I'll change it.
